### ISSUE TITLE
Dgemm unexpected fault

### ISSUE THREAD

**Issue by btracey** [gonum/blas#77]
The inner loop of the dgemmSerialNotTrans function is 
````
var tmp float64
for l, v := range b.data[j*b.stride : j*b.stride+b.cols] {
    tmp += atmp[l] * v
}
````
I tried replacing this with 
````
tmp := ddotUnitary(atmp, b.data[j*b.stride : j*b.stride+b.cols])
````
But I got the following panic:
````
brendan:~/Documents/mygo/src/github.com/gonum/blas/goblas$ go test -bench BenchmarkDgemm
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x89aa5]

goroutine 34 [running]:
runtime.gothrow(0x203890, 0x5)
	/Users/brendan/gover/go_1_4_0/src/runtime/panic.go:503 +0x8e fp=0x2083b3590 sp=0x2083b3578
runtime.sigpanic()
	/Users/brendan/gover/go_1_4_0/src/runtime/sigpanic_unix.go:29 +0x261 fp=0x2083b35e0 sp=0x2083b3590
github.com/gonum/blas/goblas.ddotUnitary(0x2083c4840, 0x3, 0xc, 0x2083b5e18, 0x3, 0x3, 0x403d000000000000, 0x1, 0x0, 0x2083ead00, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/ddot_amd64.s:61 +0x25 fp=0x2083b35e8 sp=0x2083b35e0
github.com/gonum/blas/goblas.dgemmSerialNotTrans(0x2083c4840, 0xc, 0xc, 0x4, 0x3, 0x3, 0x2083b5e00, 0x6, 0x6, 0x2, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:378 +0x1f5 fp=0x2083b3680 sp=0x2083b35e8
github.com/gonum/blas/goblas.dgemmSerial(0x6f, 0x70, 0x2083c4840, 0xc, 0xc, 0x4, 0x3, 0x3, 0x2083b5e00, 0x6, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:281 +0x16e fp=0x2083b3730 sp=0x2083b3680
github.com/gonum/blas/goblas.dgemmParallel(0x6f, 0x70, 0x2083c4840, 0xc, 0xc, 0x4, 0x3, 0x3, 0x2083b5e00, 0x6, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:142 +0x295 fp=0x2083b3880 sp=0x2083b3730
github.com/gonum/blas/goblas.Blas.Dgemm(0x6f, 0x70, 0x4, 0x2, 0x3, 0x4000000000000000, 0x2083c4840, 0xc, 0xc, 0x3, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/dgemm.go:103 +0x447 fp=0x2083b3a10 sp=0x2083b3880
github.com/gonum/blas/goblas.(*Blas).Dgemm(0x30f0c8, 0x6f, 0x70, 0x4, 0x2, 0x3, 0x4000000000000000, 0x2083c4840, 0xc, 0xc, ...)
	<autogenerated>:9 +0x1b0 fp=0x2083b3ab0 sp=0x2083b3a10
github.com/gonum/blas/testblas.dgemmcomp(0x1, 0x20bf30, 0xe, 0x2083de240, 0x220838c458, 0x30f0c8, 0x6f, 0x70, 0x4, 0x2, ...)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/testblas/dgemm.go:239 +0x36b fp=0x2083b3cb8 sp=0x2083b3ab0
github.com/gonum/blas/testblas.TestDgemm(0x2083de240, 0x220838c458, 0x30f0c8)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/testblas/dgemm.go:218 +0x456 fp=0x2083b3f40 sp=0x2083b3cb8
github.com/gonum/blas/goblas.TestDgemm(0x2083de240)
	/Users/brendan/Documents/mygo/src/github.com/gonum/blas/goblas/level3double_test.go:10 +0x70 fp=0x2083b3f78 sp=0x2083b3f40
testing.tRunner(0x2083de240, 0x302f98)
	/Users/brendan/gover/go_1_4_0/src/testing/testing.go:447 +0xbf fp=0x2083b3fd0 sp=0x2083b3f78
runtime.goexit()
	/Users/brendan/gover/go_1_4_0/src/runtime/asm_amd64.s:2232 +0x1 fp=0x2083b3fd8 sp=0x2083b3fd0
created by testing.RunTests
	/Users/brendan/gover/go_1_4_0/src/testing/testing.go:555 +0xa8b
````

@fhs -- do you know what's wrong?

**Comment by btracey** [comment]
dgemm.go line 378 is the call to ddotUnitary

**Comment by fhs** [comment]
Try switching the arguments:
```
tmp := ddotUnitary(b.data[j*b.stride : j*b.stride+b.cols], atmp)
```

For ddotUnitary(x, y), len(y) >= len(x) must be satisfied. I have a comment explaining this at the beginning of the function. It's too subtle. Maybe it should take an extra length argument so that this kind of mistake doesn't happen again: ddotUnitary(n, x, y)

**Comment by btracey** [comment]
But amp and btmp both have the same length.  A is sliced to have length
a.cols and b is sliced to have length b.cols, which are equal for this
particular transpose choice

**Comment by fhs** [comment]
I just tried it. It looks like `b.data[j*b.stride : j*b.stride+b.cols]` is not 16-byte aligned (i.e. j*b.stride is an odd number). If you replace the two MOVAPD with the unaligned version MOVUPD, it should work.

I guess this could break Ddot also.

**Comment by kortschak** [comment]
This commit message explains the address: https://codereview.appspot.com/83270049
